# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulesimulation', '0054_auto_20170728_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doublure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('required', models.BooleanField()),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('objectif_type', models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('select', 'select'), ('select-multiple', 'Select Multiple'), ('integer', 'integer')], default='radio', max_length=200)),
                ('choices', models.TextField(blank=True, default='oui, non', help_text='if the question type is "radio," "select," or "select multiple" provide a comma-separated list of options for this', null=True)),
                ('doublure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublure.Doublure')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseDoublure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doubleur', models.CharField(max_length=200)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('doublure_uuid', models.CharField(max_length=12, verbose_name='Identifiant unique de la doublure du stagiaire ')),
                ('doublure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublure.Doublure')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulesimulation.Stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='SousTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeDoublure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('doublure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublure.Doublure')),
            ],
        ),
        migrations.AddField(
            model_name='soustheme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublure.ThemeDoublure'),
        ),
        migrations.AddField(
            model_name='objectif',
            name='soustheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublure.SousTheme'),
        ),
    ]
