# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doublure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerBaseDoublure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Objectif',
            new_name='ObjectifDoublure',
        ),
        migrations.CreateModel(
            name='AnswerIntegerDoublure',
            fields=[
                ('answerbasedoublure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doublure.AnswerBaseDoublure')),
                ('body', models.IntegerField(blank=True, null=True)),
            ],
            bases=('doublure.answerbasedoublure',),
        ),
        migrations.CreateModel(
            name='AnswerRadioDoublure',
            fields=[
                ('answerbasedoublure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doublure.AnswerBaseDoublure')),
                ('body', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
            ],
            bases=('doublure.answerbasedoublure',),
        ),
        migrations.CreateModel(
            name='AnswerSelectDoublure',
            fields=[
                ('answerbasedoublure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doublure.AnswerBaseDoublure')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            bases=('doublure.answerbasedoublure',),
        ),
        migrations.CreateModel(
            name='AnswerSelectMultipleDoublure',
            fields=[
                ('answerbasedoublure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doublure.AnswerBaseDoublure')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            bases=('doublure.answerbasedoublure',),
        ),
        migrations.CreateModel(
            name='AnswerTextDoublure',
            fields=[
                ('answerbasedoublure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doublure.AnswerBaseDoublure')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            bases=('doublure.answerbasedoublure',),
        ),
        migrations.AddField(
            model_name='answerbasedoublure',
            name='objectif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublure.ObjectifDoublure'),
        ),
        migrations.AddField(
            model_name='answerbasedoublure',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doublure.ResponseDoublure'),
        ),
    ]
