# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doublure', '0002_auto_20170731_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustheme',
            name='doublure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doublure.Doublure'),
        ),
    ]
