# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublure', '0003_soustheme_doublure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectifdoublure',
            name='choices',
            field=models.TextField(blank=True, default='Validé, En cours, Difficultés', help_text='if the question type is "radio," "select," or "select multiple" provide a comma-separated list of options for this', null=True),
        ),
    ]
