# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doublure', '0004_auto_20170731_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionDoublure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_doublure', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='responsedoublure',
            name='numero_doublure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doublure.DescriptionDoublure'),
        ),
    ]
