# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublure', '0005_auto_20170731_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsedoublure',
            name='amelioration',
            field=models.TextField(blank=True, null=True, verbose_name='Axe d"amélioration'),
        ),
        migrations.AddField(
            model_name='responsedoublure',
            name='positif',
            field=models.TextField(blank=True, null=True, verbose_name='Points positifs'),
        ),
        migrations.AlterField(
            model_name='responsedoublure',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
    ]
