# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublure', '0006_auto_20170731_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsedoublure',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Thèmes abordés, situation particulières rencontrées'),
        ),
    ]
