# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublure', '0008_responsedoublure_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectifdoublure',
            name='seuil_validation',
            field=models.IntegerField(default=3),
        ),
    ]
